apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-rights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-rights
  template:
    metadata:
      labels:
        app: access-rights
    spec:
      containers:
      - name: access-rights
        image: access-rights:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: access-rights
spec:
  selector:
    app: access-rights
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
